name: newyork_times_clone_starter
description: New York Times app clone

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rflutter_alert: ^1.0.3
  cupertino_icons: ^0.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.0+2
flutter:

  uses-material-design: true
  fonts:
    - family: OldLondon
      fonts:
        - asset: assets/OldLondon.ttf

